name: getx_firebase_app
description: A Flutter app with GetX and Firebase Auth

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  google_fonts: ^6.3.0
  google_sign_in: ^7.1.1
  flutter_facebook_auth: ^7.1.2
  cloud_firestore: ^6.0.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  get_storage: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/