name: getx_firebase_app
description: A Flutter app with GetX and Firebase Auth

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  firebase_core: ^2.15.1
  firebase_auth: ^4.6.3
  google_fonts: ^4.0.4
  cloud_firestore: ^4.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/