// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDOCrDFu7VWHq0kam3ovhGuFwb19kGE6Q',
    appId: '1:956435030582:web:7601eab5a6e7a31cceee97',
    messagingSenderId: '956435030582',
    projectId: 'hhhapp-c22b5',
    authDomain: 'hhhapp-c22b5.firebaseapp.com',
    storageBucket: 'hhhapp-c22b5.firebasestorage.app',
    measurementId: 'G-LRRLZTS3H6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0DdXn8KT719DKTBHLxTXxAEYcQPsgBEc',
    appId: '1:956435030582:android:6c2f38a82dfdfcd6ceee97',
    messagingSenderId: '956435030582',
    projectId: 'hhhapp-c22b5',
    storageBucket: 'hhhapp-c22b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWiS0siuzFNOSMPU3JORD9FNf1oZdJf_0',
    appId: '1:956435030582:ios:d6e653adae269bf9ceee97',
    messagingSenderId: '956435030582',
    projectId: 'hhhapp-c22b5',
    storageBucket: 'hhhapp-c22b5.firebasestorage.app',
    iosClientId: '956435030582-rn96idp8va1rn3qbqgfbvl47ar3568s0.apps.googleusercontent.com',
    iosBundleId: 'com.example.hhhapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWiS0siuzFNOSMPU3JORD9FNf1oZdJf_0',
    appId: '1:956435030582:ios:d6e653adae269bf9ceee97',
    messagingSenderId: '956435030582',
    projectId: 'hhhapp-c22b5',
    storageBucket: 'hhhapp-c22b5.firebasestorage.app',
    iosClientId: '956435030582-rn96idp8va1rn3qbqgfbvl47ar3568s0.apps.googleusercontent.com',
    iosBundleId: 'com.example.hhhapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDOCrDFu7VWHq0kam3ovhGuFwb19kGE6Q',
    appId: '1:956435030582:web:99b6ceba7fa4d9d6ceee97',
    messagingSenderId: '956435030582',
    projectId: 'hhhapp-c22b5',
    authDomain: 'hhhapp-c22b5.firebaseapp.com',
    storageBucket: 'hhhapp-c22b5.firebasestorage.app',
    measurementId: 'G-G9ZGS2QQPP',
  );
}
